line-length = 100
select = ["E", "F", "I", "PL", "BLE", "B", "UP", "RUF"]
ignore = ["E203", "E266", "E501"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint.isort]
combine-as-imports = true
known-first-party = ["containerd_py"]