name: ci-python

on:
  push:
    branches: [ main, feat/python-refactor ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up venv
        run: |
          python -m venv .venv --without-pip
          curl -sS https://bootstrap.pypa.io/get-pip.py -o .venv/get-pip.py
          . .venv/bin/activate
          python .venv/get-pip.py
      - name: Install deps
        run: |
          . .venv/bin/activate
          pip install -e .[dev]
      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check .
      - name: Type check
        run: |
          . .venv/bin/activate
          mypy .
      - name: Tests
        run: |
          . .venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
      - name: Build
        run: |
          . .venv/bin/activate
          python -m build